version: '3.5'
services:
    backend:
        container_name: DEV_factuweb_backend_1
        hostname: factuweb_backend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app/factuweb-backend:rw
        networks:
            net:
                aliases:
                    - factuapi
networks:
    net:
        name: factuweb_net
        driver: bridge
